### PR TITLE
New internetcube install process

### PR DESCRIPTION
**Pull request by alexAubin**
Soooo opening this PR because I had some successful results with this :+1: 

Shenanigans I encountered : 
- I wanted to `git clone https://github.com/labriqueinternet/install` during the build ... but qemu doesn't like it (something about threading not being supported) ... so I ended up having to git clone the repo manually before the build and get it from the /tmp/overlay ... Maybe we can find a way to automatize this
- (unrelated to this particular dev?) Some weird issue with curl not recognizing the certificate for install.yunohost.org  ... Funnily enough that seems pretty similar to what I saw with my builds for Raspberry Pi this summer during the Buster release ... Anyway I worked around it using wget which doesn't trigger the issue
- (unrelated to this particular dev?) Had some issue about selinux triggering some issues during `apt install [somepackages]` ... fixed it by enabling `BUILD_MINIMAL='yes'` which seems to make sense to me

Other than this : having succesfully build the image for Lime2, I was able to flash it, boot, wait a few minutes, went to `internetcube.local` and happily saw the install interface and was able to setup a cube :+1: :tada: 

(No install.yunohost.org involved, no hypercube file to transfer, ...)

Any review/feedback is greatly appreciated (on this PR or the work on https://github.com/labriqueinternet/install ) - ping @HugoPoi @keomabrun :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by HugoPoi** [comment]
Can you rebase on top of yunohost branch now, because I update the builder and add some config to speed up the build ;-) ( Sorry I forgot to merge my work last week )

**Comment by alexAubin** [comment]
Alrighty I ended up recreating the branch with squashed commits because git would not let me cherry pick (not sure why)

**Comment by HugoPoi** [comment]
I will build this and test asap

**Comment by alexAubin** [comment]
ˢᵐᵒˡ ᵇᵘᵐᵖ  :eyes:

**Comment by HugoPoi** [comment]
Ok I add a git submodule on my side

**Comment by HugoPoi** [comment]
Definitely need a way to change the parameters, because I tried with domain `youpi.local` and I was stuck on the second step with a failed.
## To be perfect TODO list
- [X] the password I set had a `#` in it so your code doesn't handle escapement on args !!!!!!! bash helll
- [ ] Have a button to reset the form
- [X] I have weird issue with network, sometimes I never get DHCP working with the internetcube build
- [ ] Wifi seems not enabled by default, I had to enable it after the installation was finish through the wifi app
- [X] Small stupid bug with validating that nohost.me domain are available
- [x] Do french translation ?

**Comment by alexAubin** [comment]
Tested the build tonight ... doesn't work ... I again encounter the issue where DHCP doesn't work on Lime 2, therefore no internet access ...

**Comment by alexAubin** [comment]
Alrighty folks, two remaining items: 

- > Have a button to reset the form
   - not sure what to do with this, there's already a button "retry". But once the install started you can't really "go back to the install form" because that would imply to also completely reset yunohost (which in fact could be somewhat doable ... now that I think about it ... but still a bit touchy)

-  > Wifi seems not enabled by default, I had to enable it after the installation was finish through the wifi app
   - I guess this is gonna be fixed by the hotspot app, or ...?

**Comment by alexAubin** [comment]
alrighty i tested again, just relaunched a build because I didnt realize i had to bump the git submodule, but otherwise it's working good :+1:

**Comment by alexAubin** [comment]
Turns out after some more "final" tests I ended up implementing a "full reset" button to hopefully reset postinstall and stuff in case things go bad before it's so boring to have to re-flash the entire thing. (In my case turned out my .cube was expired)

Anyway, new tag, release candidate !

**Comment by alexAubin** [comment]
(bumpity bump, can i make riliz)

**Pull request merged**
